### ISSUE TITLE
Reloading tab2 table fails

### ISSUE THREAD

**Issue by JeanBilheux** [neutrons/FastGR#29]
Post-Processing Tab -> Reload List of Scans button.

fails for iPTS-16826 for example

**Comment by marshallmcdonnell** [comment]
<img width="841" alt="screenshot 104" src="https://cloud.githubusercontent.com/assets/17032543/20429336/1090ab44-ad5c-11e6-950f-9c118d7b6ad5.png">

**Comment by JeanBilheux** [comment]
Marshall, did you have the chance to try with an old autoNOM file and see if the same error pops up ?

**Comment by marshallmcdonnell** [comment]
Sorry Jean, I just checked.

It does work for an older IPTS (IPTS-16915). The file that is being read-in is auto_sum.inp in the older IPTS. Is this file created by FastGR?

Below, I have the auto_sum.inp files for both IPTSs (16915 on the right and 16826 on the left):
![screenshot 20](https://cloud.githubusercontent.com/assets/17032543/20433637/930f4498-ad72-11e6-9c9d-e6c1257e2794.png)

**Comment by JeanBilheux** [comment]
Thanks. That will help me debug the issue. I will try to work on it today (just pretending to list to the tutorial we have all day long ☺  ).

Those 2 IPTS will really help me figure out the issue. Thanks for doing this

Jean

**Comment by marshallmcdonnell** [comment]
It was not on your side! It was in the python script readtitles.py. 

It works now! Sorry about that and hope. I should have looked into it more first.

**Comment by JeanBilheux** [comment]
I never had such an easy bug to fix   ☺

thanks
