### ISSUE TITLE
Add option to create exp.ini without running autonom script

### ISSUE THREAD

**Issue by JeanBilheux** [neutrons/FastGR#30]

**Comment by JeanBilheux** [comment]
Can I have more detail about this work. 

My understanding is that we need a button that create the exp.ini file (usually needed by runautonNOM) but the algo should stop there... and that's it. Is that correct ?

**Comment by marshallmcdonnell** [comment]
Exactly. Create the file but do not run the autoNOM script.

The reason is that in some cases, we want to use the FastGR as an exp.ini text editor. We take the created exp.ini file to either 1) check that it looks right or 2) use it outside of FastGR.
