### ISSUE TITLE
Calculate G(r) - would like to use Rmax > 100.0

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/FastGR#52]
In the Calculate G(r) tab, currently capped at Rmax = 100.0 Angstroms, seen below: 

![image](https://cloud.githubusercontent.com/assets/17032543/20900649/16ee89da-bafd-11e6-98ca-5d8d025b2c40.png)

We cannot increase the field to say 101.00. Would like to increase the bound.

**Comment by wdzhou** [comment]
Rmax's maximum value is changed to 1000.
