### ISSUE TITLE
Job Monitor - add feedback to process that is running

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/FastGR#55]
Want to have GUI display the last, say 10, log files that have been written to based on the timestamp of the log file.

These are located in the 'logs' directory.

![screenshot from 2016-12-08 14-44-03](https://cloud.githubusercontent.com/assets/17032543/21025071/0a2eb2f6-bd55-11e6-93c1-2e5d6a11f6b3.png)

**Comment by marshallmcdonnell** [comment]
Want to have GUI display the last, say 10, log files that have been written to based on the timestamp of the log file.

These are located in the 'logs' directory.

**Comment by JeanBilheux** [comment]
can you give me the full path to this logs folder

**Comment by marshallmcdonnell** [comment]
It is `/SNS/NOM/IPTS-16391/shared/autoNOM/logs/`
