### ISSUE TITLE
Post Processing - would like to add sorting to the table via clicking on a column

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/FastGR#57]

**Comment by JeanBilheux** [comment]
Are you talking about the table of tab 2 ?

**Comment by marshallmcdonnell** [comment]
Yes, we were discussing wanting to sort based on say:
 1) the name if we select the Name column (in red below)
 2) the first run of the run list if we select Runs (in blue below)

 file:///home/ntm/Pictures/Screenshot%20from%202016-12-12%2014-32-38.png

**Comment by marshallmcdonnell** [comment]
Let's also include all the other column headers as well (Select, Sample Formula, etc.)!

**Comment by JeanBilheux** [comment]
https://github.com/neutrons/FastGR/commit/0a344ced22edc484b2ab88cabbb3dd694b6dbe92
