### ISSUE TITLE
Menu Bar - Create an Undo button in the Edit drop-down

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/FastGR#59]
Can we add an Undo feature to the GUI?

**Comment by JeanBilheux** [comment]
As I started to work on this, and because this is a big job, I thought that we can maybe start with just the table. Does that sound ok? Maybe this is the place where the users wants the Undo to take action anyway. Just want to be sure.

**Comment by JeanBilheux** [comment]
Marshall. I added the undo/redo buttons when right clicking in the table. The undo works for all the editable fields, but not for the buttons (inside the table). It won't be too hard to add them but I just want to be sure that it's really needed.
