### ISSUE TITLE
autoNOM Tab - add copystuff.py capability into autoNOM Tab

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/FastGR#70]
Want to add a section to copy files over from a previous IPTS. We have the python script that can do this `~zjn/pytest/copystuff.py`.

We will need fields for the IPTS to copy from and the name of the autoNOM directory to copy from.

**Comment by JeanBilheux** [comment]
arguments are:
-i <input IPTS>
-f <input autoNOM>
-t <output autoNOM>

**Comment by JeanBilheux** [comment]
Can you explain to me how the arguments are supposed to work because when I give him the following folders (which I thought was the way it is supposed to work)...it does not like it and try to go to some very strange IPS-9999 folder !!!!

```
/SNS/users/zjn/pytest/copystuff.py -i /SNS/NOM/IPTS-17210 -f /SNS/NOM/IPTS-17210/shared/autoNOM_02 -t /SNS/users/j35/autonNOM_remove_me

mkdir: cannot create directory /SNS/NOM/IPTS-9999/shared//SNS/users/j35/autoNOM_remove_me/': No such file or directory 
.......etc.....
```

**Comment by marshallmcdonnell** [comment]
The usage for the listed above should be as follows:

`/SNS/users/zjn/pytest/copystuff.py -i 17210 -f autoNOM_02 -t autoNOM_remove_me`
